"""Initial SettleUply schema with audit fields
Revision ID: 357357d2f437
Revises: 
"""
from alembic import op
import sqlalchemy as sa

revision = '357357d2f437'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VERIFICATION', 'PENDING_APPROVAL', 'ACTIVE', 'REJECTED', 'SUSPENDED', name='userstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_users_approved_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_users_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('categories',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_system AND user_id IS NULL) OR (NOT is_system AND user_id IS NOT NULL)', name=op.f('ck_categories_ownership')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_categories_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_categories_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_categories_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_table('contacts',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_contacts_created_by_users')),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], name=op.f('fk_contacts_linked_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_contacts_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_contacts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_table('groups',
    sa.Column('owner_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_groups_created_by_users')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_groups_owner_user_id_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_groups_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_owner_user_id'), 'groups', ['owner_user_id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('purpose', sa.Enum('REGISTRATION', 'PASSWORD_RESET', 'EMAIL_CHANGE', name='otppurpose', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('otp_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_otp_verifications_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_otp_verifications_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_verifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_verifications'))
    )
    op.create_index(op.f('ix_otp_verifications_email'), 'otp_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.create_table('payment_methods',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_system AND user_id IS NULL) OR (NOT is_system AND user_id IS NOT NULL)', name=op.f('ck_payment_methods_ownership')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payment_methods_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_payment_methods_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payment_methods_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods'))
    )
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_user_sessions_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_user_sessions_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('email_transaction_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_transaction_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_due_reminders', sa.Boolean(), nullable=False),
    sa.Column('sms_due_reminders', sa.Boolean(), nullable=False),
    sa.Column('email_settlement_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_settlement_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_group_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_group_notifications', sa.Boolean(), nullable=False),
    sa.Column('default_reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_user_settings_created_by_users')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_user_settings_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_settings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_settings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_settings_user_id'))
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_group_members_contact_id_contacts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_group_members_created_by_users')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_group_members_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_members')),
    sa.UniqueConstraint('group_id', 'contact_id', name=op.f('uq_group_members_group_id_contact_id')),
    sa.UniqueConstraint('group_id', 'user_id', name=op.f('uq_group_members_group_id_user_id'))
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('transaction_type', sa.Enum('PERSONAL_EXPENSE', 'MONEY_LENT', 'MONEY_BORROWED', name='transactiontype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('payment_method_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_SETTLED', 'SETTLED', 'OVERDUE', 'CANCELLED', name='transactionstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_sms', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(transaction_type = 'PERSONAL_EXPENSE' AND contact_id IS NULL) OR (transaction_type != 'PERSONAL_EXPENSE' AND contact_id IS NOT NULL)", name=op.f('ck_transactions_contact_type')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transactions_positive_amount')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories')),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_transactions_contact_id_contacts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_transactions_created_by_users')),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_transactions_payment_method_id_payment_methods')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_transactions_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index(op.f('ix_transactions_contact_id'), 'transactions', ['contact_id'], unique=False)
    op.create_index(op.f('ix_transactions_currency'), 'transactions', ['currency'], unique=False)
    op.create_index(op.f('ix_transactions_deleted_at'), 'transactions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_transactions_due_date'), 'transactions', ['due_date'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('group_expenses',
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('paid_by_member_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('payment_method_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('split_type', sa.Enum('EQUAL', 'EXACT', name='splittype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_group_expenses_positive_amount')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_group_expenses_category_id_categories')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_group_expenses_created_by_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_group_expenses_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_expenses_group_id_groups')),
    sa.ForeignKeyConstraint(['paid_by_member_id'], ['group_members.id'], name=op.f('fk_group_expenses_paid_by_member_id_group_members')),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_group_expenses_payment_method_id_payment_methods')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_group_expenses_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_expenses'))
    )
    op.create_index(op.f('ix_group_expenses_group_id'), 'group_expenses', ['group_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('contact_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='channel', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('notification_type', sa.String(length=60), nullable=False),
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SKIPPED', name='notificationstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_notification_logs_contact_id_contacts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_notification_logs_created_by_users')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_notification_logs_group_id_groups')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_notification_logs_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_notification_logs_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_logs'))
    )
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('reminder_type', sa.Enum('DUE_SOON', 'DUE_TODAY', 'OVERDUE', 'CUSTOM', name='remindertype', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat_interval_days', sa.Integer(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'CANCELLED', name='reminderstatus', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reminders_created_by_users')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_reminders_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_reminders_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reminders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders'))
    )
    op.create_index(op.f('ix_reminders_next_run_at'), 'reminders', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_reminders_transaction_id'), 'reminders', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('transaction_settlements',
    sa.Column('transaction_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_transaction_settlements_positive_amount')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_transaction_settlements_created_by_users')),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_transaction_settlements_payment_method_id_payment_methods')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_settlements_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_transaction_settlements_updated_by_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transaction_settlements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_settlements'))
    )
    op.create_index(op.f('ix_transaction_settlements_transaction_id'), 'transaction_settlements', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_transaction_settlements_user_id'), 'transaction_settlements', ['user_id'], unique=False)
    op.create_table('expense_splits',
    sa.Column('group_expense_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('group_member_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='created_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('updated_application_type', sa.Enum('WEB', 'MOBILE', 'SYSTEM', 'UNKNOWN', name='updated_application_type', native_enum=False, create_constraint=True), server_default='UNKNOWN', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('share_amount >= 0 AND settled_amount >= 0 AND settled_amount <= share_amount', name=op.f('ck_expense_splits_valid_share')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expense_splits_created_by_users')),
    sa.ForeignKeyConstraint(['group_expense_id'], ['group_expenses.id'], name=op.f('fk_expense_splits_group_expense_id_group_expenses')),
    sa.ForeignKeyConstraint(['group_member_id'], ['group_members.id'], name=op.f('fk_expense_splits_group_member_id_group_members')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_expense_splits_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_splits')),
    sa.UniqueConstraint('group_expense_id', 'group_member_id', name=op.f('uq_expense_splits_group_expense_id'))
    )
    op.create_index(op.f('ix_expense_splits_group_expense_id'), 'expense_splits', ['group_expense_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_splits_group_expense_id'), table_name='expense_splits')
    op.drop_table('expense_splits')
    op.drop_index(op.f('ix_transaction_settlements_user_id'), table_name='transaction_settlements')
    op.drop_index(op.f('ix_transaction_settlements_transaction_id'), table_name='transaction_settlements')
    op.drop_table('transaction_settlements')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_transaction_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_next_run_at'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_group_expenses_group_id'), table_name='group_expenses')
    op.drop_table('group_expenses')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_due_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_deleted_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_currency'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_contact_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_email'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_groups_owner_user_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
